---
name: "CLEVER Change Request"
title: "CLEVER Change Request - "
labels: "CLEVER"
description: "Generic issue to track CLEVER Changes"
body:
  - type: markdown
    attributes:
      value: "Please fill out the details involved in this change request."
  - type: markdown
    attributes:
      value: "## Request"
  - type: checkboxes
    id: scope
    attributes:
      label: Areas Affected
      description: Which areas are affected by this change?
      options:
        - label: dict.txt
        - label: neg_trigs.json
        - label: na_trigs.json
        - label: CLEVER Code Base
  - type: textarea
    id: background
    attributes:
      label: Request Background
      description: Please provide any provenance for this request.
  - type: textarea
    id: request_details
    attributes:
      label: Request Details
      description: Please provide any details for this request.
  - type: markdown
    attributes:
      value: "## Validation"
  - type: checkboxes
    id: validation_scope
    attributes:
      label: Validation Scope
      description: Where should this be validated?
      options:
        - label: Synapse
        - label: clever-rockies
  - type: textarea
    id: validation_steps
    attributes:
      label: Validation Details
      description: Please provide specific validation details.
  - type: markdown
    attributes:
      value: |
        **Validation SOP Wikis**
        [Validation dict.txt](https://github.com/dax-westerman/sandbox/wiki/Validating-dict.txt-Changes)
        [Validating Trigger Files](https://github.com/dax-westerman/sandbox/wiki/Validating-trigger-files-SOP)
        [Validating CLEVER-rockies](https://github.com/dax-westerman/sandbox/wiki/Validating-CLEVER%E2%80%90rockies-SOP)
        [Validating CLEVER Synapse](https://github.com/dax-westerman/sandbox/wiki/Validating-Synapse-Code-SOP)
---

