---
name: "Update to Dict"
title: "Terminology Update - "
labels: "dict.txt"
description: "This is a test"
body:
  - type: markdown
    attributes:
      value: "**Scope**"
  - type: markdown
    attributes:
      value: "**Background**"
  - type: markdown
    attributes:
      value: "**Request**"
  - type: markdown
    attributes:
      value: "**Validation Steps**"
  - type: checkboxes
    id: scope
    description: Which areas are affected by this change?
    attributes:
      - "dict.txt"
      - "neg_trigs.json"
      - "na_trigs.json"
      - "CLEVER Code Base"

---

