---
name: "Update to Dict"
title: "Terminology Update - "
labels: "dict.txt"
description: "This is a test"
body:
  - type: markdown
    attributes:
      value: "Please fill out the details involved in this change request."
  - type: checkboxes
    id: scope
    attributes:
      label: Change Scope
      description: Which areas are affected by this change?
      options:
        - label: dict.txt
        - label: neg_trigs.json
        - label: na_trigs.json
        - label: CLEVER Code Base
      required: true
---

